<?php

/**
 * @file
 * Primary module hooks for layoutbuilder_enhancements module.
 */


use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_access() for entity type "block".
 * 
 * Restrict the access to edit/ update the specific custom block type to administer users.
 */
function lb_enahancements_block_access(Block $block, $operation, AccountInterface $account)
{
    // The last condition is only needed if the trick from below is used with
    if (($operation == 'update' || $operation == 'edit') && $block->getPluginId() == 'custom_block_lb' && $block->id() !== NULL) {
        return AccessResult::allowedIfHasPermission($account, 'administer nodes');
    }
    return AccessResult::neutral();
}

/**
 * Implements hook_form_altr
 * 
 * Limiting the sections to be used.
 */
function lb_enahancements_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    // Ensure Layout Builder is enabled for this content type.
    // if ($form_id == 'node_article_layout_builder_form') {
    //     $node = \Drupal::routeMatch()->getParameter('node');
    //     $layoutBuilder = $node->get('layout_builder__layout');
    //     $sections = $layoutBuilder->getSections();
    //     \Drupal::logger('lb_enahancements')->notice("Section count".count($sections) );
    //     // echo count($sections);exit;
    //     $section_limit = 1; //Allow only one section
    //     if(count($sections) > $section_limit){
    //         $form_state->setErrorByName('layout_builder', t('You cannot add more than @limit sections.', ['@limit' => $section_limit]));
    //     }
    // }
  }
  